<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAGcLJ0P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAGcLJ0P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAGcLJ0P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAGcLJ0P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAGcLJ0P\App_KernelDevDebugContainer([
    'container.build_hash' => 'AGcLJ0P',
    'container.build_id' => 'e2f8e615',
    'container.build_time' => 1588430858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAGcLJ0P');
